# bazy danych

development:
  adapter: mysql2
  database: tp_dev
  pool: 5
  timeout: 5000
  username: root
  password: pass

test:
  adapter: mysql2
  database: tp_test
  pool: 5
  timeout: 5000
  username: root
  password: pass

production:
  adapter: mysql2
  database: tp
  pool: 5
  timeout:
  username: root
  password: pass

# baza danych etl

etl_execution:
  adapter: mysql2
  database: tp_etl
  pool: 5
  timeout: 5000
  username: root
  password: pass

# hurtownie danych

development_warehouse:
  adapter: postgresql
  database: tp_dev_wh
  pool: 5
  timeout: 5000
  username: postgres
  password: pass

test_warehouse:
  adapter: postgresql
  database: tp_test_wh
  pool: 5
  timeout: 5000
  username: postgres
  password: pass

production_warehouse:
  adapter: postgresql
  database: tp_wh
  pool: 5
  timeout: 5000
  username: postgres
  password: pass