# bazy danych

development: &default_db
  adapter: mysql2
  database: db/development.mysql2
  pool: 5
  timeout: 5000
  username: root
  password: pass

test:
  database: db/test.mysql2
  <<: *default_db

production:
  adapter: mysql2
  database: db/production.mysql2
  pool: 5
  timeout:
  username: root
  password: pass

# baza danych etl

etl_execution:
  database: db/etl.mysql2
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  password: pass

# hurtownie danych

development_warehouse: &default_wh
  database: db/development_warehouse.mysql2
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  password: pass

test_warehouse:
  database: db/test_warehouse.mysql2
  <<: *default

production_warehouse:
  database: db/production_warehouse.mysql2
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  password: pass