# bazy danych

development:
  adapter: mysql2
  database: db/development.mysql2
  pool: 5
  timeout: 5000
  username: root
  password: pass

test:
  adapter: mysql2
  database: db/test.mysql2
  pool: 5
  timeout: 5000
  username: root
  password: pass

production:
  adapter: mysql2
  database: db/production.mysql2
  pool: 5
  timeout:
  username: root
  password: pass

# baza danych etl

etl_execution:
  database: db/etl.mysql2
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  password: pass

# hurtownie danych

development_warehouse:
  adapter: mysql2
  database: db/development_warehouse.mysql2
  pool: 5
  timeout: 5000
  username: root
  password: pass

test_warehouse:
  adapter: mysql2
  database: db/test_warehouse.mysql2
  pool: 5
  timeout: 5000
  username: root
  password: pass

production_warehouse:
  adapter: mysql2
  database: db/production_warehouse.mysql2
  pool: 5
  timeout: 5000
  username: root
  password: pass